### ISSUE TITLE
The errors

### ISSUE THREAD

**Issue by efemery5** [hawolt/league-client-api#3]
Exception in thread "main" org.json.JSONException: JSONObject["gameData"] not found.
	at org.json.JSONObject.get(JSONObject.java:570)
	at org.json.JSONObject.getJSONObject(JSONObject.java:780)
	at com.hawolt.virtual.leagueclient.userinfo.child.UserInformationBanRestrictionData.<init>(UserInformationBanRestrictionData.java:14)
	at com.hawolt.virtual.leagueclient.userinfo.child.UserInformationBanRestriction.<init>(UserInformationBanRestriction.java:18)
	at com.hawolt.virtual.leagueclient.userinfo.child.UserInformationBan.<init>(UserInformationBan.java:25)
	at com.hawolt.virtual.leagueclient.userinfo.UserInformation.<init>(UserInformation.java:41)
	at com.hawolt.virtual.riotclient.VirtualRiotClient.createVirtualLeagueClientInstance(VirtualRiotClient.java:74)
	at com.hawolt.virtual.riotclient.VirtualRiotClient.createVirtualLeagueClientInstance(VirtualRiotClient.java:61)
	at Preset.main(Preset.java:26)

**Comment by hawolt** [comment]
Interesting, will take a look now and report back in a few minutes

**Comment by hawolt** [comment]
Fixed with the latest commit 314c4a51006a76d10b771e496a72e95406142e06
Apparently the fields are not given anymore, or atleast not always present? will need further investigation.
